# Generated by Django 4.2.5 on 2023-10-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=15, null=True)),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('slogan', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(upload_to='sliders')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('deal_percent', models.CharField(blank=True, max_length=25, null=True)),
                ('image', models.ImageField(upload_to='topbanners')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Top Banners',
            },
        ),
    ]
