# Generated by Django 4.2.5 on 2023-10-11 07:21

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('core', '0004_alter_slider_brand_alter_slider_slogan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=12, max_length=20, prefix='cat', unique=True),
        ),
        migrations.AlterField(
            model_name='main_category',
            name='mcid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=5, max_length=10, prefix='mcat', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=12, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='12345ABCDEFGH', length=8, max_length=10, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pics', to='core.product'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=12, max_length=20, prefix='ven', unique=True),
        ),
    ]
